// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package tests

import (
	"bytes"
	"html/template"
	"io"
	"net/http"
)

// <<< START TEMPLATE: Nested

var rawNestedTemplate =
// language=gotemplate
`<h1>{{.Organisation.Name}}</h1>
<p>{{.Organisation.Founded}}</p>
<div>
    <p>{{.Employee.Personal.Address.Street}}</p>
    <p>{{.Employee.Personal.Address.City}}</p>
    <p>{{.Employee.Personal.Address.Country}}</p>
</div>
`

var NestedTemplate = template.Must(template.New("Nested").Parse(rawNestedTemplate))

type NestedData struct {
	Organisation NestedOrganisation
	Employee     NestedEmployee
}

type NestedEmployee struct {
	Personal NestedEmployeePersonal
}

type NestedEmployeePersonal struct {
	Address NestedEmployeePersonalAddress
}

type NestedEmployeePersonalAddress struct {
	Street  any
	City    any
	Country any
}

type NestedOrganisation struct {
	Name    any
	Founded any
}

// Nested renders the nested.gohtml template as an HTML fragment
func Nested(data NestedData) template.HTML {
	buf := new(bytes.Buffer)
	err := RenderNested(buf, data)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderNested renders the nested.gohtml template to the specified writer.
// For writing to an http.ResponseWriter - use RenderNestedHTTP instead.
func RenderNested(w io.Writer, data NestedData) error {
	tmpl := NestedTemplate
	if LiveReload {
		var err error
		tmpl, err = template.ParseFiles("tests/nested.gohtml")
		if err != nil {
			return err
		}
	}

	return tmpl.Execute(w, data)
}

// RenderNestedHTTP renders the nested.gohtml template to the http.ResponseWriter.
// Errors are handled with the package global tests.ErrorFn function (which can be customized) and returned.
// You can choose to handle errors with the tests.ErrorFn handler, the returned error, or both.
func RenderNestedHTTP(w http.ResponseWriter, data NestedData) error {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")

	buf := new(bytes.Buffer)
	err := RenderNested(buf, data)
	if err != nil {
		ErrorFn(w, err)
		return err
	}

	return nil
}

// >>> END TEMPLATE: Nested
