// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package tests

import (
	"bytes"
	"html/template"
	"io"
	"net/http"
)

// <<< START TEMPLATE: Person

var rawPersonTemplate =
// language=gotemplate
`<p>Name: {{.Name}}</p>
<p>Age: {{.Age}}</p>
<p>Phone: {{.Contact.Phone}}</p>
<p>Email: {{.Contact.Email}}</p>
<ul>
    {{range $link := .Socials}}
        <li>{{$link.Name}} {{$link.Href}}</li>
    {{end}}
</ul>
`

var PersonTemplate = template.Must(template.New("Person").Parse(rawPersonTemplate))

type PersonData struct {
	Name    any
	Age     any
	Contact PersonContact
	Socials []PersonSocialsLink
}

type PersonContact struct {
	Phone any
	Email any
}

type PersonSocialsLink struct {
	Name any
	Href any
}

// Person renders the person.gohtml template as an HTML fragment
func Person(data PersonData) template.HTML {
	buf := new(bytes.Buffer)
	err := RenderPerson(buf, data)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderPerson renders the person.gohtml template to the specified writer.
// For writing to an http.ResponseWriter - use RenderPersonHTTP instead.
func RenderPerson(w io.Writer, data PersonData) error {
	tmpl := PersonTemplate
	if LiveReload {
		var err error
		tmpl, err = template.ParseFiles("tests/person.gohtml")
		if err != nil {
			return err
		}
	}

	return tmpl.Execute(w, data)
}

// RenderPersonHTTP renders the person.gohtml template to the http.ResponseWriter.
// Errors are handled with the package global tests.ErrorFn function (which can be customized) and returned.
// You can choose to handle errors with the tests.ErrorFn handler, the returned error, or both.
func RenderPersonHTTP(w http.ResponseWriter, data PersonData) error {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")

	buf := new(bytes.Buffer)
	err := RenderPerson(buf, data)
	if err != nil {
		ErrorFn(w, err)
		return err
	}

	_, _ = w.Write(buf.Bytes())
	w.WriteHeader(http.StatusOK)

	return nil
}

// >>> END TEMPLATE: Person
