// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package tests

import (
	"bytes"
	_ "embed"
	"html/template"
	"io"
)

//go:embed basic.gohtml
var BasicTemplate string

type BasicData struct {
	Name any
	Date any
}

// Basic renders the "Basic" template as an HTML fragment
func Basic(data BasicData) template.HTML {
	buf := new(bytes.Buffer)
	err := RenderBasic(buf, data)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderBasic renders the "Basic" template to the specified writer
func RenderBasic(w io.Writer, data BasicData) error {
	var tmpl *template.Template
	var err error
	if LiveReload {
		tmpl, err = template.ParseFiles("tests/basic.gohtml")
	} else {
		tmpl, err = template.New("Basic").Parse(BasicTemplate)
	}
	if err != nil {
		return err
	}

	return tmpl.Execute(w, data)
}
