// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package template

import (
	"bytes"
	_ "embed"
	"html/template"
	"io"
)

//go:embed hello.gohtml
var HelloTemplate string

type HelloData struct {
	Name any
	Age  any
}

// Hello renders the "Hello" template as an HTML fragment
func Hello(data HelloData) template.HTML {
	buf := new(bytes.Buffer)
	err := RenderHello(buf, data)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderHello renders the "Hello" template to the specified writer
func RenderHello(w io.Writer, data HelloData) error {
	var tmpl *template.Template
	var err error
	if LiveReload {
		tmpl, err = template.ParseFiles("template/hello.gohtml")
	} else {
		tmpl, err = template.New("Hello").Parse(HelloTemplate)
	}
	if err != nil {
		return err
	}

	return tmpl.Execute(w, data)
}
