// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package examples

import (
	"bytes"
	_ "embed"
	"html/template"
	"io"
)

//go:embed conditional.gohtml
var ConditionalTemplate string

// Conditional renders the "Conditional" template as an HTML fragment
func Conditional() template.HTML {
	buf := new(bytes.Buffer)
	err := RenderConditional(buf)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderConditional renders the "Conditional" template to the specified writer
func RenderConditional(w io.Writer) error {
	var tmpl *template.Template
	var err error
	if LiveReload {
		tmpl, err = template.ParseFiles("examples/conditional.gohtml")
	} else {
		tmpl, err = template.New("Conditional").Parse(ConditionalTemplate)
	}
	if err != nil {
		return err
	}

	return tmpl.Execute(w, nil)
}
