// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package views

import (
	"bytes"
	"html/template"
	"io"
	"net/http"
)

// --- START TEMPLATE: Page

var rawPageTemplate =
// language=gotemplate
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.Title}}</title>
    <meta name="description" content="{{.Description}}">
</head>
<body>
{{.Body}}
</body>
</html>`

var PageTemplate = template.Must(template.New("Page").Parse(rawPageTemplate))

type PageData struct {
	Title       any
	Description any
	Body        any
}

// Page renders the "Page" template as an HTML fragment
func Page(data PageData) template.HTML {
	buf := new(bytes.Buffer)
	err := RenderPage(buf, data)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderPage renders the "Page" template to the specified writer.
// If the writer is of the type http.ResponseWriter - the content-type header is set to "text/html; charset=utf-8"
func RenderPage(w io.Writer, data PageData) error {
	if hw, ok := w.(http.ResponseWriter); ok {
		hw.Header().Set("Content-Type", "text/html; charset=utf-8")
	}

	tmpl := PageTemplate
	if LiveReload {
		var err error
		tmpl, err = template.ParseFiles("example/template/conditional.gohtml")
		if err != nil {
			return err
		}
	}

	return tmpl.Execute(w, data)
}

// --- END TEMPLATE: Page
