// Code generated by gohtml. DO NOT EDIT

//go:build !ignore_autogenerated

package layout

import (
	"bytes"
	_ "embed"
	"html/template"
	"io"
)

//go:embed base.gohtml
var BaseTemplate string

type BaseData struct {
	Title any
	Body  any
}

// Base renders the "Base" template as an HTML fragment
func Base(data BaseData) template.HTML {
	buf := new(bytes.Buffer)
	err := RenderBase(buf, data)
	if err != nil {
		panic(err)
	}

	return template.HTML(buf.String())
}

// RenderBase renders the "Base" template to the specified writer
func RenderBase(w io.Writer, data BaseData) error {
	var tmpl *template.Template
	var err error
	if LiveReload {
		tmpl, err = template.ParseFiles("layout/base.gohtml")
	} else {
		tmpl, err = template.New("Base").Parse(BaseTemplate)
	}
	if err != nil {
		return err
	}

	return tmpl.Execute(w, data)
}
